# Generated by Django 2.0 on 2017-12-06 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0013_auto_20171130_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
