# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0013_auto_20171130_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
