# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0015_auto_20171214_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='aiteuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiteuser', to='rateMyCourse.User'),
        ),
    ]
